# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://alicarnold.files.wordpress.com/2009/11/new-product.jpg?w=150&h=150', upload_to='images'),
            preserve_default=False,
        ),
    ]
