# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/new-product.jpg', upload_to='images'),
        ),
    ]
